export const DEFAULT_PERMISSIONS = {
  ADMIN: [
    { module: "dashboard", action: "view" },
    { module: "pdv", action: "view" },
    { module: "pdv", action: "create" },
    { module: "pdv", action: "edit" },
    { module: "pdv", action: "delete" },
    { module: "caixa", action: "view" },
    { module: "caixa", action: "create" },
    { module: "caixa", action: "edit" },
    { module: "caixa", action: "delete" },
    { module: "caixa", action: "open" },
    { module: "caixa", action: "close" },
    { module: "estoque", action: "view" },
    { module: "estoque", action: "create" },
    { module: "estoque", action: "edit" },
    { module: "estoque", action: "delete" },
    { module: "relatorios", action: "view" },
    { module: "relatorios", action: "export" },
    { module: "usuarios", action: "view" },
    { module: "usuarios", action: "create" },
    { module: "usuarios", action: "edit" },
    { module: "usuarios", action: "delete" },
    { module: "configuracoes", action: "view" },
    { module: "configuracoes", action: "edit" },
    { module: "clientes", action: "view" },
    { module: "clientes", action: "create" },
    { module: "clientes", action: "edit" },
    { module: "clientes", action: "delete" },
  ],
  MANAGER: [
    { module: "dashboard", action: "view" },
    { module: "pdv", action: "view" },
    { module: "pdv", action: "create" },
    { module: "caixa", action: "view" },
    { module: "caixa", action: "create" },
    { module: "caixa", action: "edit" },
    { module: "caixa", action: "open" },
    { module: "caixa", action: "close" },
    { module: "estoque", action: "view" },
    { module: "estoque", action: "create" },
    { module: "estoque", action: "edit" },
    { module: "relatorios", action: "view" },
    { module: "relatorios", action: "export" },
    { module: "clientes", action: "view" },
    { module: "clientes", action: "create" },
    { module: "clientes", action: "edit" },
  ],
  CASHIER: [
    { module: "pdv", action: "view" },
    { module: "pdv", action: "create" },
    { module: "caixa", action: "view" },
    { module: "caixa", action: "create" },
    { module: "clientes", action: "view" },
    { module: "clientes", action: "create" },
  ],
  STOCK_MANAGER: [
    { module: "dashboard", action: "view" },
    { module: "estoque", action: "view" },
    { module: "estoque", action: "create" },
    { module: "estoque", action: "edit" },
    { module: "estoque", action: "delete" },
    { module: "relatorios", action: "view" },
  ],
  SALES: [
    { module: "pdv", action: "view" },
    { module: "pdv", action: "create" },
  ],
}

// Mock function to assign permissions (no database needed)
export function getDefaultPermissionsForRole(role: string) {
  return DEFAULT_PERMISSIONS[role as keyof typeof DEFAULT_PERMISSIONS] || []
}
